doc_id for pysolr.delete should be a string (#164)
pysolr.delete requires the doc_id passed to it to be a string. Otherwise,
its internal xml parsing code is unhappy (pysolr internally uses xml payloads
for solr requests in many/most cases). Also, log the complete stacktrace
in `callback_wrapper` to make debugging in case of failures easier.

For reference, one of the failing messages had the following stacktrace:

    Traceback (most recent call last):
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1014, in _escape_cdata
    if "&" in text:
    ^^^^^^^^^^^
    
    TypeError: argument of type 'int' is not iterable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    
    File "/code/sir/amqp/handler.py", line 122, in wrapper
    f(self=self, parsed_message=parsed_message)
    ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    File "/code/sir/amqp/handler.py", line 300, in delete_callback
    self.cores[core_name].delete(parsed_message.columns[column_name])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    File "/usr/local/lib/python3.13/site-packages/pysolr.py", line 1143, in delete
    m = ElementTree.tostring(et)
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1084, in tostring
    ElementTree(element).write(stream, encoding,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
    xml_declaration=xml_declaration,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    default_namespace=default_namespace,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    method=method,
    ^^^^^^^^^^^^^^
    short_empty_elements=short_empty_elements)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 729, in write
    serialize(write, self._root, qnames, namespaces,
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    short_empty_elements=short_empty_elements)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 892, in _serialize_xml
    _serialize_xml(write, e, qnames, None,
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    short_empty_elements=short_empty_elements)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 890, in _serialize_xml
    write(_escape_cdata(text))
    ~~~~~~~~~~~~~^^^^^^
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1022, in _escape_cdata
    _raise_serialization_error(text)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
    
    File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1004, in _raise_serialization_error
    raise TypeError(
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
    )
    
    TypeError: cannot serialize 279115 (type int)